@port= 8080



# MATERIAS
http://localhost:{{port}}/api/materias/1
# http://localhost:{{port}}/api/materias?pag

###
POST http://localhost:{{port}}/api/materias/ HTTP/1.1
content-type: application/json

{
    "nome": "exemplo2"
}

###
PUT http://localhost:{{port}}/api/materias/{{id}} HTTP/1.1
content-type: application/json

{
    "nome": "exemplo editado 22"
}

###
DELETE http://localhost:{{port}}/api/materias/{{id}} HTTP/1.1
content-type: application/json

###
http://localhost:{{port}}/api/materias/{{id}}/professores

###
http://localhost:{{port}}/api/materias/{{id}}/aulas




# PROFESSORES
###
http://localhost:{{port}}/api/professores/
# http://localhost:{{port}}/api/professores?pag

###
POST http://localhost:{{port}}/api/professores/ HTTP/1.1
content-type: application/json

{
    "nome": "Professor 2",
    "whatsapp": "123456789",
    "short_bio": "um professor bunitu y inteligente",
    "materias_id": [4, 7, 3, 6]
}

###
PUT http://localhost:{{port}}/api/professores/{{id}} HTTP/1.1
content-type: application/json

{
    "nome": "Professor (editado)",
    "whatsapp": "123456789",
    "short_bio": "um professor bunitu y inteligente",
    "materias_id": [1, 2, 3]
}

###
DELETE http://localhost:{{port}}/api/professores/1 HTTP/1.1
content-type: application/json

###
http://localhost:{{port}}/api/professores/{{id}}/materias

###
http://localhost:{{port}}/api/professores/{{id}}/aulas




# AULAS
###
http://localhost:{{port}}/api/aulas

###
POST http://localhost:{{port}}/api/aulas/ HTTP/1.1
content-type: application/json

{
    "materia_id": 4,
    "professor_id": 2,
    "preco": "50",
    "inicio": "12:00",
    "fim": "15:00",
    "dia": 1
}

###
PUT http://localhost:{{port}}/api/aulas/3 HTTP/1.1
content-type: application/json

{
    "preco": "70",
    "inicio": "16:00",
    "fim": "17:00",
    "dia": 2
}

###
DELETE http://localhost:{{port}}/api/aulas/2 HTTP/1.1
content-type: application/json
